declare class BaseManager extends NamespacedObject {
  constructor(game: any, namespace: any, id: any);
  game: any;
  fightInProgress: boolean;
  spawnTimer: Timer;
  notifications: NotificationQueue;
  allowDuplicateDOTS: boolean;
  isActive: boolean;
  giveFreeDeath: boolean;
  rendersRequired: {
    location: boolean;
    pause: boolean;
    slayerAreaEffects: boolean;
    eventMenu: boolean;
    areaRequirements: boolean;
    spellBook: boolean;
  };
  shouldResetAction: boolean;
  _dotID: number;
  get dotID(): number;
  initialize(): void;
  setCallbacks(): void;
  minibarEatCallback(): void;
  minibarRunCallback(): void;
  minibarShowHoldToEat(): void;
  minibarHideHoldToEat(): void;
  render(): void;
  getErrorLog(): string;
  renderSpellBook(): void;
  checkDeath(): void;
  onPlayerDeath(): void;
  onEnemyDeath(): boolean;
  addMonsterStat(statID: any, amount?: number): void;
  addCombatStat(statID: any, amount?: number): void;
  onSelection(): void;
  stop(fled?: boolean): boolean;
  loadNextEnemy(): void;
  spawnEnemy(): void;
  uniqueUpdatesOnEnemySpawn(): void;
  statUpdateOnEnemySpawn(): void;
  startFight(tickOffset?: boolean): void;
  endFight(): void;
  onCombatPageChange(): void;
  renderAutoSwapFood(): void;
  resetActionState(): void;
  encode(writer: any): any;
  decode(reader: any, version: any): void;
  deserialize(reader: any, version: any, idMap: any): void;
}
