declare function initGameClass(): void;
declare function initMenus(): void;
declare let game: any;
declare let showCombatArea: any;
declare let skillNav: any;
declare let skillProgressDisplay: any;
declare let spendMasteryMenu: any;
declare let enemyHTMLElements: any;
declare let playerHTMLElements: any;
declare let thievingMenu: any;
declare let firemakingMenu: any;
declare let woodcuttingMenu: any;
declare let eventManager: any;
declare let herbloreArtisanMenu: any;
declare let herbloreCategoryMenu: any;
declare const herbloreSelectionTabs: Map<any, any>;
declare let potionSelectMenu: any;
declare let smithingArtisanMenu: any;
declare const smithingSelectionTabs: Map<any, any>;
declare let smithingCategoryMenu: any;
declare let altMagicMenu: any;
declare let altMagicItemMenu: any;
declare let altMagicSelection: any;
declare let runecraftingCategoryMenu: any;
declare let runecraftingArtisanMenu: any;
declare const runecraftingSelectionTabs: Map<any, any>;
declare let craftingCategoryMenu: any;
declare let craftingArtisanMenu: any;
declare const craftingSelectionTabs: Map<any, any>;
declare let fletchingCategoryMenu: any;
declare let fletchingArtisanMenu: any;
declare const fletchingSelectionTabs: Map<any, any>;
declare let summoningArtisanMenu: any;
declare const summoningSelectionTabs: Map<any, any>;
declare let summoningCategoryMenu: any;
declare const markDiscoveryMenus: Map<any, any>;
declare let summoningSearchMenu: any;
declare const fishingAreaMenus: Map<any, any>;
declare const cookingMenus: Map<any, any>;
declare const agilityObstacleMenus: any[];
declare let agilityPassivePillarMenu: any;
declare let agilityElitePassivePillarMenu: any;
declare const agilityObstacleSelectMenus: any[];
declare let astrologyMenus: any;
declare let farmingMenus: any;
declare let townshipUI: any;
declare let bankTabMenu: any;
declare let bankOptionsMenu: any;
declare let bankMoveModeMenu: any;
declare let bankSellModeMenu: any;
declare let bankSideBarMenu: any;
declare let bankItemSettingsMenu: any;
declare const combatSkills: string[];
declare let shopMenu: any;
declare namespace synergyElements {
    const icons: any[];
    const tooltips: any[];
}
declare let tutorialMenus: any;
declare let combatMenus: any;
declare let areaMenus: any;
