declare class FiremakingLog extends BasicSkillRecipe {
  constructor(namespace: any, data: any, game: any);
  log: any;
  baseInterval: any;
  baseBonfireInterval: any;
  bonfireXPBonus: any;
  get name(): any;
  get media(): any;
}
declare class Firemaking extends CraftingSkill {
  constructor(namespace: any, game: any);
  bonfireTimer: Timer;
  baseAshChance: number;
  baseStardustChance: number;
  baseCharcoalChance: number;
  _media: string;
  modifiers: MappedModifiers;
  renderQueue: FiremakingRenderQueue;
  getTotalUnlockedMasteryActions(): any;
  get noCostsMessage(): any;
  get actionInterval(): number;
  get masteryModifiedInterval(): number;
  get actionLevel(): any;
  get masteryAction(): any;
  get activeRecipe(): any;
  get activeBonfire(): any;
  get isBonfireActive(): boolean;
  get isLogSelected(): boolean;
  get generousFireSpiritChance(): number;
  get coalChance(): any;
  get diamondChance(): number;
  get bonfireBonusXP(): any;
  get ashChance(): number;
  get charcoalChance(): number;
  get ashQty(): number;
  getStardustChance(log: any): number;
  get isBearDevilActive(): boolean;
  coalItem: any;
  diamondItem: any;
  ashItem: any;
  fireSpiritItem: any;
  charcoalItem: any;
  computeProvidedStats(updatePlayer?: boolean): void;
  onEquipmentChange(): void;
  queueBankQuantityRender(item: any): void;
  localize(): void;
  burnLog(): void;
  getCurrentRecipeCosts(): Costs;
  getFiremakingGPMultiplier(): number;
  recordCostConsumptionStats(costs: any): void;
  recordCostPreservationStats(costs: any): void;
  preAction(): void;
  get actionRewards(): Rewards;
  postAction(): void;
  endBonFire(): void;
  litBonfireRecipe: any;
  lightBonfire(): void;
  selectedRecipe: any;
  setFromOldOffline(offline: any, idMap: any): void;
  getActionIDFromOldID(oldActionID: any, idMap: any): any;
  selectLog(recipeToSelect: any): void;
  renderBonfireStatus(): void;
  renderFireProgress(): void;
  renderBonfireProgress(): void;
  renderSelectedLog(): void;
  renderSelectedLogQty(): void;
  renderLogSelection(): void;
}
declare class FiremakingRenderQueue extends GatheringSkillRenderQueue {
  selectedLog: boolean;
  bonfireProgress: boolean;
  bonfireStatus: boolean;
  logQty: boolean;
}
