declare function fetchLanguageJSON(lang: any): any;
declare function setLanguage(lang: any): any;
declare function localiseSwal2(): void;
declare function updateUIForLanguageChange(): void;
declare function getLangString(key: any, identifier: any): any;
declare var __awaiter: any;
declare let setLang: string;
declare let loadedLangJson: any;
declare const langVersion: 624;
declare const LANGS: string[];
declare let SwalLocale: any;
